@baseUrl = http://localhost:3000

### @name indexSecret
# @prompt secretId
GET {{baseUrl}}/api/{{secretId}}

### @name openSecret
# @prompt secretId
PATCH {{baseUrl}}/api/{{secretId}}
Content-Type: application/json

{
  "passphrase": "123"
}

### @name storeSecret
POST {{baseUrl}}/api
Content-Type: application/json

{
  "content": "hello world",
  "type": "text",
  # "mime": "image/png",
  # "filename": "file.png",
  "passphrase": "test",
  "short": true,
  "ttl": 300
}
